
function getEasyWord(){
  var easyWords = [
  "wide",
  "goods",
  "tufts",
    "same",
    "cove",
    "mask",
    "gift",
    "mess",
    "drill",
    "post",
    "logs",
    "upon",
    "feet",
    "sprung",
    "plates",
    "bread",
    "loud",
    "beak",
    "foam",
    "oil",
    "also",
    "spikes",
    "smug",
    "shelter",
    "frankly",
    "found",
    "bonnet",
    "camera",
    "single",
    "Texas",
    "alas",
    "embers",
    "slumped",
    "circus",
    "imagined",
    "part",
    "nook",
    "cold",
    "much",
    "thing",
    "hike",
    "very",
    "left",
    "meet",
    "bent",
    "hat",
    "idea",
    "must",
    "zoomed",
    "matching",
    "clock",
    "flapped",
    "cog",
    "clutch",
    "gushed",
    "floor",
    "speech",
    "rapids",
    "creak",
    "knot",
    "gloves",
    "rodeo",
    "wrenches",
    "polish",
    "mumble",
    "barrels",
    "paddles",
    "blurted",
    "aware",
    "reveal",
    "mink",
    "jelly",
    "lane",
    "deer",
    "try",
    "car",
    "last",
    "rush",
    "lid",
    "mice",
    "swim",
    "singing",
    "turning",
    "large",
    "track",
    "crusts",
    "cell",
    "poor",
    "knife",
    "china",
    "frames",
    "shoe",
    "slide",
    "gutter",
    "search",
    "pretty",
    "salad",
    "goggles",
    "dolphin",
    "direct",
    "clerks",
    "whiskers",
    "wallet",
    "mango",
    "ached",
    "tummy",
    "slow",
    "son",
    "silk",
    "duckling",
    "rage",
    "well",
    "gone",
    "lisp",
    "rope",
    "read",
    "kites",
    "wanted",
    "closed",
    "chart",
    "pain",
    "cheese",
    "power",
    "place",
    "stopped",
    "studied",
    "prize",
    "goals",
    "booth",
    "crouched",
    "baskets",
    "cousin",
    "inflate",
    "skiing",
    "detail",
    "forty",
    "condition",
    "focus",
    "firmly",
    "fabric"
];

var randomItem = easyWords[Math.floor(Math.random()*easyWords.length)];
  document.getElementById("word").innerText = randomItem;
}

function getMediumWord(){
  var mediumWords = [
  "detour",
  "teachers",
  "gusto",
    "scarf",
    "shimmery",
    "blindfolded",
    "clobbered",
    "rattled",
    "throat",
    "scuba",
    "absent",
    "savor or savour",
    "inclined",
    "masthead",
    "leghorn",
    "crockery",
    "neptune",
    "lavished",
    "nada",
    "adorned",
    "invasions",
    "destination",
    "scrawny",
    "mulberry",
    "weird",
    "mutual",
    "alibi",
    "devious",
    "flaxen",
    "biome",
    "cardigan",
    "withered",
    "lincon",
    "tartan",
    "wretched",
    "expanse",
    "contessa",
    "wreaked",
    "sudoku",
    "exerts",
    "reflexology",
    "fetlocks",
    "pulverized or pulverised"
   
];

var randomItem = mediumWords[Math.floor(Math.random()*mediumWords.length)];
  document.getElementById("word").innerText = randomItem;
}

function getHardWord(){
  var hardWords = [
  "Hard",
  "School",
  "Gymnastics"
];

var randomItem = hardWords[Math.floor(Math.random()*hardWords.length)];
  document.getElementById("word").innerText = randomItem;
}
